# Generated by Django 4.2.4 on 2023-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_editors_choice",
            field=models.BooleanField(default=False),
        ),
    ]
