# Generated by Django 4.2.4 on 2023-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_is_editors_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"get_latest_by": "createdAt"},
        ),
    ]
