# Generated by Django 4.2.4 on 2023-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0007_subcategory_slug"),
        ("posts", "0010_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post_tags", to="category.tag"
            ),
        ),
    ]
