# Generated by Django 4.2.4 on 2023-08-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0007_subcategory_slug"),
        ("posts", "0011_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_posts",
                to="category.topic",
            ),
        ),
    ]
