# Generated by Django 4.2.4 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_tag_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_top_story",
            field=models.BooleanField(default=False),
        ),
    ]
