# Generated by Django 4.2.4 on 2023-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0005_topic_is_top_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
