# Generated by Django 4.2.4 on 2023-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0006_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
